HOSTS:
  ubuntu-12-04:
    platform: ubuntu-12.04-x64
    image: ubuntu:12.04
    hypervisor: docker
    docker_preserve_image: true
    docker_image_commands: 
      - 'mkdir -p /root/.ssh'
    #  - 'apt-get install -y puppet' 
  centos6:
    platform: centos-6-x64
    image: centos:centos6
    hypervisor: docker
    docker_preserve_image: true
CONFIG:
  type: foss

